### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by martinweihrauch** [petebankhead/qupath#10]
Hi Pete:
Could you contact me (I did not find any e-mail, etc of yours): info (at) smartinmedia (dot) com
Thanks

Martin

**Comment by petebankhead** [comment]
Hi, I sent an email to this address.  Please reopen this if you didn't receive it and I'll try again.

([Google Groups](https://groups.google.com/forum/#!forum/qupath-users) is another way to get in contact - you can *Reply privately to the author* of any posts there)
