### ISSUE TITLE
How to detect cells/annoations by positive pixel count?

### ISSUE THREAD

**Issue by bpuladi** [petebankhead/qupath#20]
I have done the positive pixel count on acertain region on Giemsa/DAB tissue. Now I want to seperate it into different cells or annoations. But I did not found no solution for that. The "Cell detection" does not work on my kind of tissue (brainstem tissue).
![screenshot01](https://user-images.githubusercontent.com/44176896/47271886-b9d25e00-d57d-11e8-818f-e03fe9175df4.jpg)

**Comment by petebankhead** [comment]
Since this isn't the main QuPath repository, and is intended for issues/bugs rather than questions, I'd suggest posting your question on Google Groups, where more people are likely to see it and may give suggestions: https://groups.google.com/forum/#!forum/qupath-users
