### ISSUE TITLE
Handling qdata file in python for making annotation mask

### ISSUE THREAD

**Issue by abhijeetptl5** [petebankhead/qupath#21]
After annotating WSI image, we get qdata file. I want to access coordinates of annotations we made using qdata file in python.

I am currently using ImageScope which generates XML file corresponding to annotated regions, which is easy to handle. Is there any way to convert qdata file to xml or csv file?

**Comment by petebankhead** [comment]
There are lots of related discussions about this, e.g. 
* https://groups.google.com/d/msg/qupath-users/qGhTHcBe6aw/lW3XAZcfBQAJ
* https://github.com/qupath/qupath/issues/140
* https://github.com/qupath/qupath/issues/95

If you search on [Google Groups](https://groups.google.com/forum/#!forum/qupath-users) you may well find others.  QuPath can't write ImageScope's XML (to be able to support this, the XML format would need to have an openly-available specification), but through a script you can export in any way you like... but this requires defining the format precisely and writing the script.

I will close this as it the question is better suited to Google Groups, and is not an issue/bug with QuPath.
