### ISSUE TITLE
Positive cell detection: parameters changing between image tiles

### ISSUE THREAD

**Issue by skalteis** [petebankhead/qupath#22]
Hi Peter,

I just build qupath master (68d01b203463451f962740b8449f39bba9d505ac) from your development github repository and noticed strange behaviour in the positive cell detection algorithm.

The image I am using is an NDPI, I just ran tissue detection to set up an ROI and ran positive cell detection without changes to the parameters. The result can be seen in the image below, the algorithm's settings seem to change from image tile to tile. Cell shapes seem to get cut at the tile boundary as well.

The system is running Linux (Debian 9.0, OpenJDK 8).

Thank you for developing QuPath & best regards from Heidelberg! :-)

Simon

![qupath-bugreport](https://user-images.githubusercontent.com/4951046/50224355-04b1fb80-039e-11e9-8d15-e5e52bc9ccfa.jpg)

**Comment by skalteis** [comment]
closer look at a tile boundary: note the difference in the number of detections and the cut cell shapes at the border
![bugreport_qupath2](https://user-images.githubusercontent.com/4951046/50225685-7dff1d80-03a1-11e9-90c0-9bd8ede82f4f.png)

**Comment by petebankhead** [comment]
Hi Simon,

Greetings back to you in Heidelberg :)

This looks like the same issue as described at https://github.com/qupath/qupath/issues/80
If I'm right, you would see the same if you use QuPath v0.1.2 as well.  If not, then I'd need to investigate what has changed...

The above link also includes my explanation for what it's a limitation more than a bug, and also possible workarounds.

**Comment by skalteis** [comment]
Oh, sorry, should have checked the stable repository as well... you are right, I see this with 0.1.2 as well.
I'll try the suggestions there, thanks a lot!
