### ISSUE TITLE
Running Qupath in server/headless/commandline mode

### ISSUE THREAD

**Issue by lloonngg** [petebankhead/qupath#23]
We are looking to deploy Qupath for clinical use for IHC counting.  Is there a way to interface with Qupath via commandline w/o the GUI to run batch processes on whole slide images?  Specifically, we want to to provide an image, a csv of coordinates for regions of interest, and have Qupath segment cells and count within the area of interest.  Is this possible to do via command line or terminal?

Long

**Comment by petebankhead** [comment]
There's a discussion about this [here](https://groups.google.com/d/msg/qupath-users/7cdsBsdy4HQ/faFXwPN3BgAJ).

Basically, there is some limited command line support in v0.1.2 and some other options you could investigate (i.e. using the QuPath .jars within a custom wrapper program that handles whatever else you need).

My priority currently is to have a new, overhauled software release before March and continue actively developing it afterwards.  I plan to revisit the command line support, but at this point I'm not sure if I'll manage to squeeze it in by March or not.

If you can describe a bit more precisely how this would ideally look, I'll give it some more thought.  For example, what command line arguments you'd expect to need to pass, and in what form the output should be.
